- CHANGELOG.md
- lib/event_sourcery/postgres/event_store.rb
- lib/event_sourcery/postgres/schema.rb
In https://github.com/envato/event_sourcery/pull/157 we added a `causation_id` attribute to the `Event` class and added the expectation that all Event Sourcery event stores will persist this value.
Update the PostgreSQL event store so that it persists the `causation_id` event attribute. This includes adding a column to the `events` table and updating the `write_events` function to populate it.
We'll need to ensure that all Event Sourcery applications make this schema change when upgrading to the next version of Event Sourcery. Is the entry to the change log enough notice?
Although there are no specs added here. There is some covering this change in the event store shared RSpec examples provided by the `event_sourcery` gem. The build will be broken till this change is applied.
In a …
> Event Store persists causation_id

- lib/event_sourcery/postgres/event_store.rb
- spec/event_sourcery/postgres/event_store_spec.rb
This PR adds support for using any class that can be converted to string with `.to_str`  as `aggregate_id` when loading and persisting events.
In one of our apps we are using `UUIDTools::UUID` as aggregate ids. We have to explicitly convert such ids to strings in our code to pass them to `EventStore` to load aggregate events because Sequel cannot implicitly convert them to strings.
> Convert aggregate id to string

- CHANGELOG.md
- Gemfile
- lib/event_sourcery/postgres/event_store.rb
- lib/event_sourcery/postgres/schema.rb
In https://github.com/envato/event_sourcery/pull/125 we added a `correlation_id` attribute to the `Event` class. Then in https://github.com/envato/event_sourcery/pull/160 we added the expectation that all Event Sourcery event stores will persist this value.
Similar to #18: update the PostgreSQL event store so that it persists the `correlation_id` event attribute. This includes adding a column to the `events` table and updating the `write_events` function to populate it.
We'll need to ensure that all Event Sourcery applications make this schema change when upgrading to the next version of Event Sourcery.
Although there are no specs added here. There are some covering this change in the event store shared RSpec examples provided by the `event_sourcery` gem. The build will be broken till …
> Postgres event store persists correlation_id

- spec/event_sourcery/postgres/reactor_spec.rb
Changed here: https://github.com/envato/event_sourcery/pull/162.
> Fix in-memory event store and tracker references

- CHANGELOG.md
- Gemfile
- event_sourcery-postgres.gemspec
- lib/event_sourcery/postgres/version.rb
- Allow pushing to rubygems.org
- Bump version to 0.3.0
- No longer need to source `event_sourcery` from GitHub
> Bump version and stop blocking pushes to rubygems.org

- CHANGELOG.md
- Gemfile
- event_sourcery-postgres.gemspec
- lib/event_sourcery/postgres/reactor.rb
- spec/event_sourcery/postgres/reactor_spec.rb
When an event is emitted from a reactor we want to record which event we were processing at the time. This is a great aid to debugging.
Currently we record this fact by storing the event id of the event being processed in the emitted event's body with the attribute name `_driven_by_event_id`.
This PR proposes to change this to store the UUID of the event being processed in the `causation_id` attribute of the emitted event.
> Reactors Populate Event Causation Id

- CHANGELOG.md
- lib/event_sourcery/postgres/schema.rb
Add two indexes to the `events` table. One for `correlation_id` and one for `causation_id`.
I'm a little concerned with the number of indexes on this table now. Are there any we can remove? `created_at` perhaps.
> Add indexes for `correlation_id` and `causation_id`

- CHANGELOG.md
- lib/event_sourcery/postgres/reactor.rb
- spec/event_sourcery/postgres/reactor_spec.rb
When an event is emitted from a reactor we want its `correlation_id` to be the same as the `correlation_id`  of the event being processed.
Also move the `causation_id` changelog entry up to the unreleased section. It didn't make version 0.3. Bad merge added it at the wrong location.
> Reactor populates correlation id

- lib/event_sourcery/postgres/tracker.rb
- spec/event_sourcery/postgres/tracker_spec.rb
Table name needs to be a symbol. Lets ensure it gets converted to a
symbol.
When you define the table_name as a string it gives the following error:
```
Sequel::DatabaseError:
PG::SyntaxError: ERROR:  syntax error at or near "tracker"
LINE 1: tracker
^
```
> Coerce table name to a symbol

- CHANGELOG.md
- event_sourcery-postgres.gemspec
- lib/event_sourcery/postgres/version.rb
* Remove a few unrequired files from the gem package
* Set Envato as the author
* Bump version 0.3.0 -> 0.4.0
* Mark changes as released in changelog
> Preparation for 0.4.0 release

- .travis.yml
Get build status notifications in our Slack channel. Only reports upon status change so should be extremely low volume so long as no-one breaks master.
> Slack build notifications

- CHANGELOG.md
- lib/event_sourcery/postgres/projector.rb
- spec/event_sourcery/postgres/projector_spec.rb
This matches the behaviour of [EventStreamProcessor][1] in event_sourcery.
We're using the block form of log which makes the testing slightly more verbose but means we don't need to evaluate the string if the logging level doesn't require the message to be logged.
[1]: https://github.com/envato/event_sourcery/blob/87d2dae6d18a460a2a6e69cbb315ea08863695d8/lib/event_sourcery/event_processing/event_stream_processor.rb#L155-L163
> Only send info log after processing a group of events

- CHANGELOG.md
- lib/event_sourcery/postgres/projector.rb
- spec/event_sourcery/postgres/projector_spec.rb
- spec/event_sourcery/postgres/reactor_spec.rb
`processes_events` is being removed from `event_sourcery` https://github.com/envato/event_sourcery/pull/161.
> Remove processes_events and projects_events in favour of process and project class methods

- lib/event_sourcery/postgres/config.rb
- spec/event_sourcery/postgres/event_store_spec.rb
Ruby produces several warnings while running our test suite:
https://travis-ci.org/envato/event_sourcery-postgres/jobs/322722599
This change set resolves these warnings:
```
event_sourcery-postgres/lib/event_sourcery/postgres/config.rb:29: warning: method redefined; discarding old event_store
event_sourcery-postgres/lib/event_sourcery/postgres/config.rb:33: warning: method redefined; discarding old event_source
event_sourcery-postgres/lib/event_sourcery/postgres/config.rb:37: warning: method redefined; discarding old event_sink
event_sourcery-postgres/lib/event_sourcery/postgres/config.rb:41: warning: method redefined; discarding old event_store_database=
event_sourcery-postgres/lib/event_sourcery/postgres/config.rb:47: warning: method redefined; discarding old projections_database= …
```
> Resolve Ruby Warnings

- CHANGELOG.md
- event_sourcery-postgres.gemspec
Version 5.3 of the Sequel gem has been released. The specs pass on this new version.
Anyone have concerns about removing this restriction?
> Remove version restriction on Sequel gem

- CHANGELOG.md
Link from versions in `CHANGELOG.md` to GitHub compare pages. This gives quick access to see the changes in code between versions.
> Change log versions link to GitHub compare pages

- spec/event_sourcery/postgres/optimised_event_poll_waiter_spec.rb
Ruby 2.5.0 changed the default of Thread.report_on_exception to true. This thread is meant to raise an exception.
https://bugs.ruby-lang.org/issues/14143
> Don't report thread exceptions in spec when using Ruby 2.5+

- CHANGELOG.md
- lib/event_sourcery/postgres/config.rb
- lib/event_sourcery/postgres/projector.rb
- spec/event_sourcery/postgres/projector_spec.rb
The process_events method may be called with 1 or more events. It then loops through each event, opens a transaction and processes the event.
This change allows specifying the number of events to process before closing the transaction.
Processing more events inside the transactions should lead to speed increases in most cases.
> Allow specifying a transaction size when projecting multiple events

- event_sourcery-postgres.gemspec
Following on from envato/event_sourcery#205. Add project metadata URIs to the gem spec. This makes more information available via the RubyGems API which in turn helps automated tools like Unwrappr obtain information about the project and individual releases.
https://guides.rubygems.org/specification-reference/#metadata
> Add project metadata URIs to the gem spec

- CHANGELOG.md
- lib/event_sourcery/postgres/config.rb
- lib/event_sourcery/postgres/event_store.rb
- lib/event_sourcery/postgres/version.rb
- spec/event_sourcery/postgres/event_store_spec.rb
This PR introduces the `on_events_recorded` hook to the Config class.
This hook will run on as the last thing on `EventStore#sink`  and can be used to do any work specific to your application when the events are recorded to the event store. Eg, passing stats to Datadog or any other service like that.
Once this PR is approved I add a commit to bump the version and update the Changelog.
> Introduce on_events_recoded hook to config and EventStore

- .travis.yml
- CHANGELOG.md
- event_sourcery-postgres.gemspec
Since Bundler 2.0 was released, our build has failed:
In our CI we install the [latest version of Bundler (2.0.1)](https://travis-ci.org/envato/event_sourcery-postgres/jobs/475125992#L472), but our gemspec [specifies we must use `~> 1.10`](https://travis-ci.org/envato/event_sourcery-postgres/jobs/475125992#L481) which excludes version 2.
To fix this:
* remove the constraint on the Bundler version from the gemspec
* ensure the latest version of Rubygems is installed, and
* remove Ruby 2.2 from the build matrix (Bundler 2.0 is not available on this version of Ruby)
> Fix the CI Build

- .travis.yml
- CHANGELOG.md
Ruby 2.6 has been [released](https://www.ruby-lang.org/en/news/2018/12/25/ruby-2-6-0-released/)! Let's add it to the test matrix.
> Test on Ruby 2.6

- CHANGELOG.md
- event_sourcery-postgres.gemspec
This resolves the security issue: CVE-2020-8130.
> Update Rake to version 13

- lib/event_sourcery/postgres/schema.rb
I'm just getting started with building an application with event sourcery and had the following error when creating the database. I'm using Postgres 11 and the following error is generated when trying to create the aggregates table unless a default constraint is added.
Thanks for open sourcing all the hard work y'all have done. Reading through the readmes and example application I'm looking forward to trying it out.
```
Sequel::DatabaseError:
PG::InvalidParameterValue: ERROR:  identity column type must be smallint, integer, or bigint
```
> Add default value constraint for uuid primary key

- .travis.yml
We're only interesting in build failures when they occur on the `master` branch.
Disable Slack for all but the `master` branch.
[TravisCI condition documentation](https://config.travis-ci.com/ref/job/if/condition)
> Only send slack notifications for builds on the master branch

- .travis.yml
- CHANGELOG.md
- lib/event_sourcery/postgres/event_store.rb
Resolve the following warnings raised when running on Ruby 2.7.
```
/event_sourcery-postgres/lib/event_sourcery/postgres/event_store.rb:122: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/event_sourcery-4ac4f7c83b32/lib/event_sourcery/event_store/event_builder.rb:8: warning: The called method `build' is defined here
/event_sourcery-postgres/lib/event_sourcery/postgres/event_store.rb:110: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/event_sourcery-4ac4f7c83b32/lib/event_sourcery/event_store/subscription.rb:15: warning: The called method `initialize' is defined here
> Resolve Ruby 2.7 warnings

- .github/workflows/test.yml
- CHANGELOG.md
- spec/support/warnings.rb
Add Ruby 3.0 to the test matrix to ensure this library works as expected.
> Test on Ruby 3.0 in CI

- .github/workflows/test.yml
- CHANGELOG.md
Ruby 2.3, 2.4 and 2.5 have reached their EOL. 
We removing dropping test matrixes for those ruby versions.
- We were unable to find an Envato application using this gem with one of the above ruby versions
- We will reach out to Envato engineering before releasing a new gem
- A new version will be released in the next  PR
> Remove Ruby 2.3, 2.4 and 2.5 from the CI test matrix

- CHANGELOG.md
- lib/event_sourcery/postgres/version.rb
Bump the new version 0.9.0. The changelog is already up to date.
We will be following the "[release](https://github.com/envato/event_sourcery#release)" document for releasing the new gem version.
> Bump version 0.9.0

- CHANGELOG.md
- lib/event_sourcery/postgres/event_store.rb
We are working on clearing out the deprecation warnings for our app as we've moved to ruby 2.7 and are getting ready for 3.x. During the process we had the following warning show up...
```bash
/app/vendor/bundle/ruby/2.7.0/gems/sequel-5.52.0/lib/sequel/dataset/actions.rb:150: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/app/vendor/bundle/ruby/2.7.0/gems/event_sourcery-postgres-0.9.0/lib/event_sourcery/postgres/event_store.rb:121: warning: The called method `build_event' is defined here
```
Forgive me if I've got this one wrong but the `**` in the line `def build_event(**data)` is used to convert keyword arguments passed to (like `build_event(foo: 1, bar: 2)`) it to a single hash variable ((like `{ foo: 1, bar: 2 }`). I am not …
> deprecated last arg keyword param event store

- CHANGELOG.md
- lib/event_sourcery/postgres/version.rb
Bump the new version 0.9.1. The changelog is already up to date.
We will be following the "[release](https://github.com/envato/event_sourcery#release)" document for releasing the new gem version.
> Bump version 0.9.1
